// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddContractModal: typeof import('./src/components/AddContractModal.vue')['default']
    AddRealtyModal: typeof import('./src/components/AddRealtyModal.vue')['default']
    ContractList: typeof import('./src/components/ContractList.vue')['default']
    EditUserModal: typeof import('./src/components/EditUserModal.vue')['default']
    EditUserPasswordModal: typeof import('./src/components/EditUserPasswordModal.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    PlacementList: typeof import('./src/components/PlacementList.vue')['default']
    RealtyList: typeof import('./src/components/RealtyList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectDateTimeButton: typeof import('./src/components/SelectDateTimeButton.vue')['default']
    SelectDateTimeModal: typeof import('./src/components/SelectDateTimeModal.vue')['default']
    SelectRealtyButton: typeof import('./src/components/SelectRealtyButton.vue')['default']
    SelectRealtyModal: typeof import('./src/components/SelectRealtyModal.vue')['default']
    SelectUserButton: typeof import('./src/components/SelectUserButton.vue')['default']
    SelectUserModal: typeof import('./src/components/SelectUserModal.vue')['default']
    SignModal: typeof import('./src/components/SignModal.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
  }
}
