/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/contract': RouteRecordInfo<'/contract', '/contract', Record<never, never>, Record<never, never>>,
    '/contracts': RouteRecordInfo<'/contracts', '/contracts', Record<never, never>, Record<never, never>>,
    '/placement': RouteRecordInfo<'/placement', '/placement', Record<never, never>, Record<never, never>>,
    '/placements': RouteRecordInfo<'/placements', '/placements', Record<never, never>, Record<never, never>>,
    '/realties': RouteRecordInfo<'/realties', '/realties', Record<never, never>, Record<never, never>>,
    '/realty': RouteRecordInfo<'/realty', '/realty', Record<never, never>, Record<never, never>>,
    '/report/salary': RouteRecordInfo<'/report/salary', '/report/salary', Record<never, never>, Record<never, never>>,
    '/reports': RouteRecordInfo<'/reports', '/reports', Record<never, never>, Record<never, never>>,
    '/user': RouteRecordInfo<'/user', '/user', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }
}
