export const REALTY_KIND_ROOM = 'Room';
export const REALTY_KIND_BUILDING = 'Building';
export const REALTY_KIND_APARTMENT = 'Apartment';
export const REALTY_KINDS = [
  REALTY_KIND_ROOM,
  REALTY_KIND_BUILDING,
  REALTY_KIND_APARTMENT,
];
export const REALTY_KIND_OF = {
  ROOM: REALTY_KIND_ROOM,
  BUILDING: REALTY_KIND_BUILDING,
  APARTMENT: REALTY_KIND_APARTMENT,
};
